//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoginHistory
    {
        public int LoginID { get; set; }
        public string Username { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
    
        public virtual tblStatu tblStatu { get; set; }
        public virtual tblClient tblClient { get; set; }
    }
}
