//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblToken
    {
        public int TokenID { get; set; }
        public string TokenCode { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblClient tblClient { get; set; }
    }
}
